### ISSUE TITLE
filling a bucket with lunar water from a cauldron does not work correctly

### ISSUE THREAD

**Issue by NyanMC** [Rebirth-of-the-Night/Nyx#3]
having a cauldron full of lunar water and attempting to scoop it into a bucket will void the fluid entirely.
from what it looks like, the issue stems from the item not changing from minecraft:bucket to forge:bucketfilled, as the nbt on the bucket is changed to what the nbt on forge:bucketfilled would need to be to create a bucket of lunar water.

steps to reproduce:
1. fill a cauldron with water, and transform it into lunar water
2. attempt to pick up the lunar water in a bucket and not a bottle
3. fluid will be voided, as it disappears from the cauldron and does not fill your bucket

**Comment by democat3457** [comment]
is inspirations installed

**Comment by NyanMC** [comment]
inspirations is not installed

**Comment by democat3457** [comment]
Fixed with 8cec1283e00e645ea69972b5bcf3bfa9de483842, should be out in next update
